### ISSUE TITLE
Problem Rosenbrock with (x₁-2)²+(x₂-2)²=2

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/SolverTest.jl#15]
I had a problem with the equality-constrained problem "Rosenbrock with (x₁-2)²+(x₂-2)²=2" as it possesses several infeasible stationary points. I think for several solvers, in particular, these are still considered as a success.
Would it be ok to remove this problem? @abelsiqueira

**Comment by abelsiqueira** [comment]
Yes, I think it's ok.

**Comment by dpo** [comment]
What is the problem? It is really useful for solvers to be able to detect infeasible stationary points, and it's useful for us to know that a solver "lies" by declaring a success when finding an infeasible stationary points.

**Comment by tmigot** [comment]
For all problems, we test whether the solver finds the solution [1, 1] with success.

However, the solver might converge to an infeasible stationary point, in which case the status is not :success, but :infeasible most of the time. In this scenario, the test fails because we didn't get [1, 1] as the solution.

**Comment by dpo** [comment]
Would it make sense to check that the solver's final iterate and status are sensical?

**Comment by tmigot** [comment]
It would be great actually. 
So, instead of checking whether the solution is a vector of 1s or not, we could have a function to check the KKT conditions if the status is :success and check infeasible-KKT conditions otherwise.
It is just a bit tricky to play with the tolerances for the stationarity conditions.

**Comment by dpo** [comment]
Well that would be awesome but significantly more difficult. I was thinking of something simpler:
* check if the solution is infeasible, if yes, check that the solver status is not `:first_order`
* if the solution is feasible, check that it is the expected solution.

That's a bit restrictive but maybe sufficient for the current unit test?

Writing a KKT checker is also interesting. Basically, you could solve an LP to find multipliers associated with x (if there are any).

**Comment by tmigot** [comment]
Okay, but if the solver fails. It will most likely return an infeasible solution with a status different from `:first_order`, and then pass the test.
