### ISSUE TITLE
Debug `multiprecision_nlp`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/SolverTest.jl#22]
I am using this for https://github.com/tmigot/FletcherPenaltyNLPSolver/pull/34, and I noticed a couple of things:
- :ineq problem https://github.com/JuliaSmoothOptimizers/SolverTest.jl/blob/ab04eb5a44bfb28f30ca9410d780c6a701e345b7/src/nlp/multiprecision.jl#L29 makes ones(2) not feasible, so the test [L. 48](https://github.com/JuliaSmoothOptimizers/SolverTest.jl/blob/ab04eb5a44bfb28f30ca9410d780c6a701e345b7/src/nlp/multiprecision.jl#L48) is impossible.
- The same issue is in the nls version https://github.com/JuliaSmoothOptimizers/SolverTest.jl/blob/ab04eb5a44bfb28f30ca9410d780c6a701e345b7/src/nls/multiprecision.jl#L29
- :equ problem https://github.com/JuliaSmoothOptimizers/SolverTest.jl/blob/ab04eb5a44bfb28f30ca9410d780c6a701e345b7/src/nlp/multiprecision.jl#L27 is ok, however it has more than one stationary point, for instance `ipopt` finds `[-0.9391944977145056,   1.0573143787609525]` with Lagrange multiplier `λ=[0.6629175882079664]`

**Comment by abelsiqueira** [comment]
Thanks for finding these issues. Can you open pull requests to fix them?
